
Create table mot(
  id Number(6) Generated By Default on Null as Identity,
  chaine Varchar2(32) Not Null,
  CONSTRAINT pk_mot_id Primary Key (id) 
);

Create table Concurrence(
  id Number(8) Generated By Default on Null as Identity,
  idMot1 Number(6),
  idMot2 Number(6),
  nbConcurrences Number(4),
  fenetre Number(5),
  CONSTRAINT pk_concurrence_id Primary Key(id),
  CONSTRAINT fk_concurrence_mot1 Foreign Key(idMot1) References mot(id),
  CONSTRAINT fk_concurrence_mot2 Foreign Key(idMot2) References mot(id)
  );
  
  Commit;